// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXWOXnZEMfrIm3M7JXNE-uXT5BTAOU_A',
    appId: '1:609938427662:web:6b58100dad57596f26515f',
    messagingSenderId: '609938427662',
    projectId: 'dressme-18b1b',
    authDomain: 'dressme-18b1b.firebaseapp.com',
    storageBucket: 'dressme-18b1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTC1w4fyzp15soIYLRdGgzNDDpou3Mk7U',
    appId: '1:609938427662:android:e96f1a95ee3bf15a26515f',
    messagingSenderId: '609938427662',
    projectId: 'dressme-18b1b',
    storageBucket: 'dressme-18b1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjX1oOhFxq9QNMKNO3nlt7OhHDUwYCpH8',
    appId: '1:609938427662:ios:468f1dca27b6ed1f26515f',
    messagingSenderId: '609938427662',
    projectId: 'dressme-18b1b',
    storageBucket: 'dressme-18b1b.appspot.com',
    iosBundleId: 'com.example.dressme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjX1oOhFxq9QNMKNO3nlt7OhHDUwYCpH8',
    appId: '1:609938427662:ios:4f159841132f6e9b26515f',
    messagingSenderId: '609938427662',
    projectId: 'dressme-18b1b',
    storageBucket: 'dressme-18b1b.appspot.com',
    iosBundleId: 'com.example.dressme.RunnerTests',
  );
}
